import Header from "@/components/header";
import SideBar from "@/components/sidebar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-8 p-8">
          <div className="min-w-[220px]">
            <SideBar />
          </div>
          <section className="flex-1">
            <Header />
            {children}
          </section>
        </div>
      </body>
    </html>
  );
}
